### PR TITLE
Changed class name for drivers to use str class and use ucwords

### PR DESCRIPTION
**Pull request by dmyers**
Signed-off-by: Derek Myers arcticpro@gmail.com

### CODE REVIEW

**Comment by WanWizard** [comment]
They need prefixing with a backslash ( \Str ), it's in the global namespace.

**Comment by dmyers** [comment]
@WanWizard Thanks for looking so fast. Good catch! I sort of rushed it a bit. :+1: 

I went ahead and just updated it.

**Comment by WanWizard** [comment]
Thanks. Any particular reason why you needed this (just curious)?

**Comment by dmyers** [comment]
Yeah I noticed I was setting my driver name as User_Auth which the strfirst made it so that the class name was Auth_Login_User_auth instead of Auth_Login_User_Auth.

I actually noticed this in some things I am working on which I based off of the driver system in auth. May not be a huge deal since autoloader is smart enough to still work with it.

**Comment by WanWizard** [comment]
Ok, thought so, just checking... :smile:

**Pull request merged**
