### PR TITLE
Fixed the ORM ACL issue with array_flip and actions check

### PR DESCRIPTION
**Pull request by mumnik**
Signed-off-by: Dayan <j.kurpnieks@gmail.com>

### CODE REVIEW

**Comment by WanWizard** [comment]
You've replaced tabs by spaces, can you fix that? Also, please explain in the comments why this is needed.

**Comment by mumnik** [comment]
I've tried to implement ORM ACL with full range check: area, permission, action and have discovered that actions check works incorrect in the array_flip section. Flipped actions from Auth_User->userpermission are being verified against not flipped $Auth_User->permissions returning empty array from the array_intersect_key(). Also flipped action actions array is  being checked on line 288 with in_array() function which also doesn't work, so I flipped them back after the array_intersect_key()

**Comment by mumnik** [comment]
.. a kind reminder

**Comment by WanWizard** [comment]
Sorry, haven't had time to check. Busy with ORM issues, and my brain only "works" for 2 hours a day max...

**Comment by mumnik** [comment]
May I help with ORM somehow?

**Comment by WanWizard** [comment]
I think most of the issues have been fixed now, only need confirmation.

Only one still open is https://github.com/fuel/orm/pull/435 which is tricky to solve without a major performance impact (which is why the proposed PR isn't merged).

**Pull request merged**
