### PR TITLE
Tell users how to edit settings

### PR DESCRIPTION
**Pull request by AD7six**
Users should not be editing package files to achieve config changes - but they are, because they don't know how else to do so.

### CODE REVIEW

**Comment by jschreuder** [comment]
Instructions like these don't belong in here, they should go into the docs repo.

**Comment by AD7six** [comment]
I agree - where are they in the docs @jschreuder?

**Comment by jschreuder** [comment]
https://github.com/fuel/docs

**Comment by WanWizard** [comment]
Oops, sorry, missed this discussion and just updated them. 

I found it a good idea (not withstanding the fact that it should be in the docs as well)

**Pull request closed without merging**
