### PR TITLE
1.6/develop

### PR DESCRIPTION
**Pull request by abread**
Hi, I made a simple change that I thought it will be good to add.
I'm developing a project in FuelPHP and to increase even more the safety of PBKDF2 I added a simple bit of code that allows the developers to change the auth iterations number!

Thanks!

PS I'm new to git and github. Did I make this in the right way?
PPS You may find some errors in my spelling but I'm not a native english speaker. I'm portuguese.

### CODE REVIEW

**Comment by WanWizard** [comment]
Can you document the new configuration key on the auth intro page, and explain what this does (not every user knows what "iterations" are).

**Comment by abread** [comment]
I was about to try add a commit to this pull request but I'm not sure in how to do it... Made the changes in another pull request located in fuel/docs. link: https://github.com/fuel/docs/pull/510

**Comment by WanWizard** [comment]
You can't. Two different repositories, so that requires to pull requests.

**Comment by abread** [comment]
Ok, thanks.

**Pull request merged**
