### PR TITLE
Improved ACL rights checking to allow heirarchical area specification

### PR DESCRIPTION
**Pull request by kbanman**
This lets you more finely assign rights to areas; Currently you can only pass a string for the area, so you're limited to one level of wildcards, among other limitations.

I needed this change for my project because I'd like to specify rights by `module`, `controller`, and optionally `action`. With this change I can do this as follows:

```
// Controller->before()
$authed = Auth::has_access(array(
    array($this->request->module, $this->request->controller, $this->request->action), 
    array('read', 'update')
));

// config/simpleauth.php
'roles' => array(
    '#' => array( // default rights
        'website' => array('read')
    ),
    'banned' => false,
    'user' => array(
        'comments' => array('create', 'read'),
        'test' => array(
            '#' => array('read'),
            'protected' => array('create', 'delete'),
        )
    ),
    'moderator' => array(
        'comments' => array('update', 'delete')
    ),
    'admin' => array(
        '#' => array('delete'),
        'website' => array('create', 'update', 'delete'),
        'admin' => array('create', 'read', 'update', 'delete'),
        'mymodule' => array(
            '#' => array('read'),
            'mycontroller' => array(
                '#' => array('update'),
                'myactionmethod' => array('delete'),
            ),
    ),
    'super' => true,
),
```

I've done some informal testing, since I'm not sure how I would put this in a test case due to sessions and whatnot.

### CODE REVIEW

**Comment by jschreuder** [comment]
Don't have time to take a good look now, but this looks like it goes far outside the scope of what the Simple\* drivers are meant to do. They were never meant as a one-size-fits-all solution, more a stepping stone with a little bit of power for Q&D solutions.  
On first glance I'd say no, too complicated. I would however encourage you to release the driver yourself as a possible plugin.

**Comment by jschreuder** [comment]
Now I had the time to look into this, but I must admit this looks very wrong to me and half of it doesn't make sense to me.

If you check multiple areas and merge the rights each role has for these areas what happens when I have a role that has full crud rights for the first area and just read rights for the second? All your rights are merged so suddenly the role has full crud rights on both areas. That really makes no sense at all to me...

Also if the rights returned is boolean (as you're checking on lines 85-94) it would already have thrown notices for you trying to use it as an array on line 57 (and if it doesn't because isset() suppresses that it's still incredible bad practice).

Even if it worked I still think the idea is too complicated, but this doesn't look like it would work properly.

**Comment by kbanman** [comment]
I assure you the logic is correct; It hurt my brain getting it there, but I've tested it to work. As for what happens when the first area has CRUD and another lower in the heirarchy has less, the merging at higher levels applies only to wildcards. I would have thought that was the expected effect, but now I can see how in some cases it wouldn't be. Easily fixed.

And yes, I should be checking if it's an array on line 57.

**Comment by jschreuder** [comment]
If the logic is correct you need to comment more or explain better how it's supposed to work, because if this takes me more than 10 minutes to figure out it's just too complex. I should get this quicker.

The merging part still makes no sense to me. You using a logic that means something like "if the user has a right that belongs to one of these areas, doesn't matter which". That's accidents waiting to happen, if you combine the wrong areas you give some user crazy rights for that page. The only way this might work is if you would require a user to have that specific right in all (not some) areas instead of just the one.
But in all cases it seems like the easier way would be to run something like this:

```
$rights = array('read', 'update');
$authed = Auth::has_access(array($this->request->module, $rights))
    and Auth::has_access(array($this->request->controller, $rights))
    and Auth::has_access(array($this->request->action, $rights));
```

That's a lot clearer and far more powerfull, because that how I think it should work (a right must be in ALL), but to mimic your code (must be in ANY):

```
$authed = Auth::has_access(array($this->request->module, $rights))
    or Auth::has_access(array($this->request->controller, $rights))
    or Auth::has_access(array($this->request->action, $rights));
```

But as I said, I think this is over-complicated to be in a driver called "SimpleAcl". For any driver you release yourself its fine, though I would recommend some more explanation both in and outside of the code if you do share it.

**Pull request closed without merging**
